#JPA configuration

spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL8Dialect


  datasource:
    url: jdbc:mysql://localhost:3306/labSQL
    username: angel
    password: 1152069
    driver-class-name: com.mysql.cj.jdbc.Driver
  web:
    resources:
      static-locations:
        -classpath:/static/
